/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TechnologyIndexRouteImport } from './routes/technology/index'
import { Route as StoreIndexRouteImport } from './routes/store/index'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as ContactIndexRouteImport } from './routes/contact/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologyIndexRoute = TechnologyIndexRouteImport.update({
  id: '/technology/',
  path: '/technology/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreIndexRoute = StoreIndexRouteImport.update({
  id: '/store/',
  path: '/store/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact/': typeof ContactIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/store/': typeof StoreIndexRoute
  '/technology/': typeof TechnologyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/store': typeof StoreIndexRoute
  '/technology': typeof TechnologyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact/': typeof ContactIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/store/': typeof StoreIndexRoute
  '/technology/': typeof TechnologyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contact/' | '/guides/' | '/store/' | '/technology/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contact' | '/guides' | '/store' | '/technology'
  id: '__root__' | '/' | '/contact/' | '/guides/' | '/store/' | '/technology/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactIndexRoute: typeof ContactIndexRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  StoreIndexRoute: typeof StoreIndexRoute
  TechnologyIndexRoute: typeof TechnologyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology/': {
      id: '/technology/'
      path: '/technology'
      fullPath: '/technology/'
      preLoaderRoute: typeof TechnologyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/': {
      id: '/store/'
      path: '/store'
      fullPath: '/store/'
      preLoaderRoute: typeof StoreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact/'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactIndexRoute: ContactIndexRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  StoreIndexRoute: StoreIndexRoute,
  TechnologyIndexRoute: TechnologyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
